[colors]
draw_bold_text_with_bright_colors=true

[colors.primary]
background = "#1e1e1e"
foreground = "#d4d4d4"


[colors.normal]
black = "#1e1e1e"
red = "#f44747"
green = "#608b4e"
yellow = "#dcdcaa"
blue = "#569cd6"
magenta = "#c678dd"
cyan = "#56b6c2"
white = "#d4d4d4"

[colors.bright]
black = "#545454"
red = "#f44747"
green = "#608b4e"
yellow = "#dcdcaa"
blue = "#569cd6"
magenta = "#c678dd"
cyan = "#56b6c2"
white = "#d4d4d4"

[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR="2"

[font]
size = 11

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[terminal.shell]
program = "/bin/bash"

[window.dimensions]
columns=160
lines=80

[window.padding]
x=0
y=0

[window]
decorations="Full"
startup_mode="Maximized"


